### ISSUE TITLE
Minor thing about help message

### ISSUE THREAD

**Issue by ozdemiremrah81** [DeploymentArtist/SWP1#3]
It's not an actual issue. 
Just adding it to inform you, at line 20 Help Message is confusing. This script is nothing to do with password. 
Btw its working without any problem but, when you try to understand what it is doing, that line is confusing :)
parameter(mandatory=$true,HelpMessage="Please, provide the password to be used.

**Comment by arwidmark** [comment]
Thanks, updated the script.
